# Generated by Django 4.2 on 2023-04-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breweries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=40)),
                ('website', models.CharField(max_length=40)),
                ('filepath', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('last_mod', models.CharField(max_length=20)),
            ],
        ),
    ]
