# Generated by Django 4.2 on 2023-05-02 12:20

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', location_field.models.plain.PlainLocationField(max_length=63)),
                ('state', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=40)),
                ('website', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=1024)),
                ('last_mod', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_mod', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_mod', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S')),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beers.category')),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alcohol_by_volume', models.FloatField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('last_mod', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S')),
                ('brewery_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beers.brewery')),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beers.category')),
                ('style_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beers.style')),
            ],
        ),
    ]
