# Generated by Django 4.2 on 2023-05-02 12:55

import beers.models
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='BreweryGeocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('accuracy', enumchoicefield.fields.EnumChoiceField(enum_class=beers.models.AccuracyEnum, max_length=18)),
                ('brewery_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beers.brewery')),
            ],
        ),
    ]
