# Generated by Django 4.2 on 2023-04-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breweries',
            name='filepath',
        ),
    ]
