# Generated by Django 4.2 on 2023-05-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_alter_brewery_city_brewerygeocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='last_mod',
            field=models.DateTimeField(auto_now_add=True, verbose_name='%Y-%m-%d %H:%M:%S'),
        ),
    ]
