# Generated by Django 4.2 on 2023-04-29 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_remove_breweries_filepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreweriesGeocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('accuracy', models.CharField(max_length=20)),
                ('brewery_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beers.breweries')),
            ],
        ),
    ]
