# Generated by Django 4.2 on 2023-04-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_breweriesgeocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=30)),
                ('last_mod', models.CharField(max_length=20)),
            ],
        ),
    ]
