# Generated by Django 4.2 on 2023-04-29 19:22

import beers.models
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0005_beerstyles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ibu', models.IntegerField()),
                ('srm', models.IntegerField()),
                ('upc', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('last_mod', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S')),
            ],
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=40)),
                ('website', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=1000)),
                ('last_mod', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S')),
            ],
        ),
        migrations.CreateModel(
            name='BreweryGeocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', enumchoicefield.fields.EnumChoiceField(enum_class=beers.models.AccuracyEnum, max_length=18)),
                ('brewery_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beers.brewery')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=30)),
                ('last_mod', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=50)),
                ('last_mod', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S')),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beers.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='beerstyles',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='breweriesgeocode',
            name='brewery_id',
        ),
        migrations.DeleteModel(
            name='BeerCategories',
        ),
        migrations.DeleteModel(
            name='BeerStyles',
        ),
        migrations.DeleteModel(
            name='Breweries',
        ),
        migrations.DeleteModel(
            name='BreweriesGeocode',
        ),
        migrations.AddField(
            model_name='beer',
            name='brewery_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beers.brewery'),
        ),
        migrations.AddField(
            model_name='beer',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beers.category'),
        ),
        migrations.AddField(
            model_name='beer',
            name='style_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beers.style'),
        ),
    ]
