# Generated by Django 4.2 on 2023-04-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0006_beer_brewery_brewerygeocode_category_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='last_mod',
            field=models.DateTimeField(),
        ),
    ]
