# Generated by Django 4.2 on 2023-04-29 19:49

import beers.models
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0007_alter_brewery_last_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewerygeocode',
            name='accuracy',
            field=enumchoicefield.fields.EnumChoiceField(enum_class=beers.models.AccuracyEnum, max_length=11),
        ),
    ]
