# Generated by Django 4.2 on 2023-04-29 20:01

import beers.models
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0008_alter_brewerygeocode_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewerygeocode',
            name='accuracy',
            field=enumchoicefield.fields.EnumChoiceField(enum_class=beers.models.AccuracyEnum, max_length=18),
        ),
    ]
