# Generated by Django 4.2 on 2023-04-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0009_alter_brewerygeocode_accuracy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewery',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='brewery',
            name='address2',
        ),
        migrations.AddField(
            model_name='beer',
            name='abv',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='brewery',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='last_mod',
            field=models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='brewerygeocode',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='brewerygeocode',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
