# Generated by Django 4.2 on 2023-04-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0010_remove_brewery_address1_remove_brewery_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='upc',
            field=models.IntegerField(default=0),
        ),
    ]
