# Generated by Django 4.2 on 2023-04-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0011_alter_beer_upc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='abv',
            new_name='alcohol_by_volume',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='ibu',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='srm',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='upc',
        ),
    ]
