# Generated by Django 4.2 on 2023-05-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0012_rename_abv_beer_alcohol_by_volume_remove_beer_ibu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='style',
            old_name='style_name',
            new_name='name',
        ),
    ]
